# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rope_bot_controller

  rope_bot_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_M_Revolute-33
      - cONNECTOR_Revolute-34
      - Joint_M3_Revolute-45
      - cONNECTOR1_Revolute-46
      - Joint_M5_Revolute-58
      - cONNECTOR2_Revolute-59
      - Joint_M7_Revolute-66
      - cONNECTOR3_Revolute-67
    action_ns: follow_joint_trajectory
    default: true