# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rope_bot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rope_bot_controller:
  ros__parameters:
    joints:
      - Joint_M_Revolute-33
      - cONNECTOR_Revolute-34
      - Joint_M3_Revolute-45
      - cONNECTOR1_Revolute-46
      - Joint_M5_Revolute-58
      - cONNECTOR2_Revolute-59
      - Joint_M7_Revolute-66
      - cONNECTOR3_Revolute-67
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true