# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - AX-12A-02_Revolute-6
      - AX-12A-021_Revolute-9
      - AX-12A-022_Revolute-12
    action_ns: follow_joint_trajectory
    default: true