# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rope_joint_controller

  rope_joint_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_M_Revolute-33
      - cONNECTOR_Revolute-34
    action_ns: follow_joint_trajectory
    default: true