# Default initial positions for BIAS_bot's ros2_control fake system

initial_positions:
  ArmV3_arm_1_main_3_Revolute-16: 0
  ArmV3_arm_1_main_Revolute-10: 0
  Servo_dummy4_Revolute-20: 0
  Shoulder_Revolute-1: 0