# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - Shoulder_Revolute-1
      - ArmV3_arm_1_main_Revolute-10
      - ArmV3_arm_1_main_3_Revolute-16
      - Servo_dummy4_Revolute-20
    action_ns: follow_joint_trajectory
    default: true